apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myntra
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /myntra
            pathType: Prefix
            backend:
              service:
                name: myntra-service
                port:
                  number: 3000

                  